#!/usr/bin/env python3
import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".JPEG", ".JPG", ".PNG"}


def load_label_json(path):
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data["results"]


def iter_images(root_dir):
    root = Path(root_dir)
    for wnid_dir in sorted(root.iterdir()):
        if not wnid_dir.is_dir():
            continue
        wnid = wnid_dir.name
        for img_path in sorted(wnid_dir.iterdir()):
            if img_path.is_file() and img_path.suffix in IMAGE_EXTS:
                yield wnid, img_path


def build_exp_name(wnid, neuron_name, num_thresholds, T, label_idx):
    if neuron_name == "IF":
        threshold_tag = "N"
    else:
        threshold_tag = str(num_thresholds)
    return f"{wnid}_{neuron_name}_{threshold_tag}_{T}_{label_idx}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--image-root",
        type=str,
        required=True,
        help="Root dir, e.g. /data/home/cxy/SNN-feat-language/data/imagenet/auxiliary_2000",
    )
    parser.add_argument(
        "--labels-json",
        type=str,
        required=True,
        help="JSON generated by build_wnid_command_labels.py",
    )
    parser.add_argument(
        "--output-root",
        type=str,
        default="/data/home/cxy/SNN-feat-language/results/CLIP",
        help="Root directory for all experiment outputs",
    )
    parser.add_argument(
        "--script",
        type=str,
        default="test_sample_metrics.py",
        help="Path to test_sample_metrics.py",
    )
    parser.add_argument(
        "--thre-path",
        type=str,
        required=True,
        help="Threshold checkpoint path",
    )
    parser.add_argument(
        "--neuron-name",
        type=str,
        choices=["IF", "MTH"],
        required=True,
    )
    parser.add_argument(
        "--num-thresholds",
        type=int,
        default=1,
    )
    parser.add_argument(
        "--T",
        type=int,
        required=True,
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda:0",
    )
    parser.add_argument(
        "--cuda-visible-devices",
        type=str,
        default=None,
        help='Optional CUDA_VISIBLE_DEVICES, e.g. "1"',
    )
    parser.add_argument(
        "--max-images",
        type=int,
        default=None,
        help="Optional debug limit",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only print commands, do not run",
    )
    args = parser.parse_args()

    label_data = load_label_json(args.labels_json)
    output_root = Path(args.output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    env = os.environ.copy()
    if args.cuda_visible_devices is not None:
        env["CUDA_VISIBLE_DEVICES"] = args.cuda_visible_devices

    num_run = 0
    num_skip = 0

    for wnid, img_path in iter_images(args.image_root):
        if wnid not in label_data:
            print(f"[SKIP] no labels for {wnid}: {img_path}")
            num_skip += 1
            continue

        paths = label_data[wnid].get("paths", [])
        if not paths:
            print(f"[SKIP] empty label paths for {wnid}: {img_path}")
            num_skip += 1
            continue

        for label_idx, item in enumerate(paths, start=1):
            labels = item["labels"]
            exp_name = build_exp_name(
                wnid=wnid,
                neuron_name=args.neuron_name,
                num_thresholds=args.num_thresholds,
                T=args.T,
                label_idx=label_idx,
            )

            # 防止同一个 WNID 下多张图片互相覆盖
            output_dir = output_root / exp_name / img_path.stem

            cmd = [
                sys.executable,
                args.script,
                str(img_path),
                *labels,
                "--thre-path",
                args.thre_path,
                "--neuron-name",
                args.neuron_name,
                "--num-thresholds",
                str(args.num_thresholds),
                "--T",
                str(args.T),
                "--device",
                args.device,
                "--output-dir",
                str(output_dir),
            ]

            print("[RUN]", " ".join(f'"{x}"' if " " in x else x for x in cmd))

            if not args.dry_run:
                output_dir.mkdir(parents=True, exist_ok=True)
                subprocess.run(cmd, env=env, check=True)

            num_run += 1
            if args.max_images is not None and num_run >= args.max_images:
                print("Reached --max-images limit.")
                print("Run:", num_run, "Skip:", num_skip)
                return

    print("Done.")
    print("Run:", num_run)
    print("Skip:", num_skip)


if __name__ == "__main__":
    main()